version: "3.9"

services:

  api:
    build: ./gptchatbot-api
    container_name: secgptchatbot-api
    ports:
      - "8000:8000"
    volumes:
      - ./gptchatbot-api:/app
    environment:
      - PYTHONPATH=/app
      - DJANGO_SETTINGS_MODULE=gptchatbot.settings
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - redis
    restart: always


  celery:
    build: ./gptchatbot-api
    container_name: secgptchatbot-celery
    command: celery -A gptchatbot worker --loglevel=info
    volumes:
      - ./gptchatbot-api:/app
    environment:
      - PYTHONPATH=/app
      - DJANGO_SETTINGS_MODULE=gptchatbot.settings
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - redis
    restart: always


  redis:
    image: redis:7-alpine
    container_name: secgptchatbot-redis
    ports:
      - "6379:6379"
    restart: always


  ui:
    build: ./gptchatbot-ui
    container_name: secgptchatbot-ui
    ports:
      - "8001:8001"
    volumes:
      - ./gptchatbot-ui:/app
      - ./gptchatbot-api:/gptchatbot-api
    environment:
      - PYTHONPATH=/app:/gptchatbot-api
      - DJANGO_SETTINGS_MODULE=gptchatbot.settings
    depends_on:
      - api
    restart: always
